configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/beats-ai-beatsfoundation%2Fbeats-foundation-c69335a9a5cf6f9453d6208489731ae0058c4194756019a2b13e2fa24604cf95.yml
