configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/beats-ai-beatsfoundation%2Fbeats-foundation-9e8f99d19503143b44d679b3743fc6791e0f6ece45048c58926ed10376d78af5.yml
